# Generated by Django 4.2.7 on 2023-12-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller_app', '0003_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
    ]
