# Generated by Django 4.2.7 on 2023-12-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller_app', '0004_alter_reserva_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['fecha_reserva']},
        ),
    ]
